name: cell-painting-vae
channels:
- conda-forge
dependencies:
- conda-forge::python
- conda-forge::pandas
- conda-forge::keras
- conda-forge::tensorflow
- conda-forge::scipy 
- conda-forge::xlrd
- conda-forge::numpy
- conda-forge::scikit-learn=0.20.3
- conda-forge::dask-ml
- conda-forge::umap-learn
- conda-forge::matplotlib
- conda-forge::seaborn
- conda-forge::hiplot
- conda-forge::plotnine
- conda-forge::jupyter
- conda-forge::jupyterlab
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::python-annoy
- conda-forge::numba
- conda-forge::pip
- pip:
#   - git+https://github.com/cytomining/pycytominer@17a1a6e3db113d72ee0d0dc934973fba00708054
#   - keras-tuner
  - cmapPy
  - h5py==2.10.0
  - pacmap